sudo: false
version: 1.0
dist: xenial

language: node_js
node_js:
  - "12"

cache:
  directories:
    - "node_modules"

jobs:
  include:
    - stage: test
      name: test
      script: npm test
      if: branch != master
    - stage: test
      name: coverage
      script: npm run coveralls
      if: branch = master
    - stage: deploy
      name: npm
      deploy:
        edge: true
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        tag: latest
        on:
          tags: true
stages:
  - test
  - name: deploy
    if: tag IS present
